### ISSUE TITLE
Find out if upgrading fast-json-patch to 3.0.0-1 is okay

### ISSUE THREAD

**Issue by JSAssassin** [digitalbazaar/bedrock-account#23]

**Comment by mattcollier** [comment]
I found that this project does not keep a changelog, but it has notes on the releases here: https://github.com/Starcounter-Jack/JSON-Patch/releases

Which tells us that that v3 now exports ES6 modules without a bundler.  This is probably breaking for folks who are still expecting a browser bundle instead of an ES6 modules. 

For our use here in Node.js though, it would appear that everything stays the same.  There are no documented API changes as a result of any of this.  So for Node.js use, this should be a fine upgrade.  Hopefully we have some tests in our test suite that exercise our use of this module in some way to ensure that it is getting loaded properly etc.  

The person that implements this update should evaluate our code coverage to ensure that this functionality is tested and that it continues to work properly after the v3 bump.

**Comment by dlongley** [comment]
Addressed by PR #29.
